name: tcga-brca
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - r-base
  - r-tidyverse
  - r-rmarkdown
  - r-irkernel
  - r-survival
  - r-survminer
  - bioconductor-deseq2
  - bioconductor-tcgabiolinks
  - bioconductor-summarizedexperiment
  - bioconductor-clusterprofiler
  - bioconductor-org.hs.eg.db
  - bioconductor-enhancedvolcano
  - pip:
    - pydeseq2
    - gseapy
    - lifelines
